import numpy as np

TWO_PI = 2 * np.pi
HBAR_J_S = 1.054571817e-34
ELEMENTARY_CHARGE_C = 1.602176634e-19
MICROELECTRONVOLT_TO_JOULE = 1e-6 * ELEMENTARY_CHARGE_C
NANOSECOND_TO_SECOND = 1e-9
MICROSECOND_TO_SECOND = 1e-6
RAD_PER_NS_PER_MICROELECTRONVOLT = (
    MICROELECTRONVOLT_TO_JOULE * NANOSECOND_TO_SECOND / HBAR_J_S
)
RAD_PER_US_PER_MICROELECTRONVOLT = (
    MICROELECTRONVOLT_TO_JOULE * MICROSECOND_TO_SECOND / HBAR_J_S
)
